services:
  db:
    image: postgres:16
    container_name: cve-postgres
    environment:
      POSTGRES_DB: cve_db
      POSTGRES_USER: cve_user
      POSTGRES_PASSWORD: cve_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
