"""create initial tables

Revision ID: c6a10757ed2c
Revises: 
Create Date: 2026-03-20 13:33:19.949153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a10757ed2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve_catalog',
    sa.Column('cve_id', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), nullable=False),
    sa.Column('affected_version_start', sa.String(length=50), nullable=False),
    sa.Column('affected_version_end', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reference_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('cve_id')
    )
    op.create_table('scan_targets',
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('target_id')
    )
    op.create_table('scan_results',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('vuln_category', sa.String(length=100), nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['scan_targets.target_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('tech_stacks',
    sa.Column('stack_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('stack_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('identify_method', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['scan_targets.target_id'], ),
    sa.PrimaryKeyConstraint('stack_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tech_stacks')
    op.drop_table('scan_results')
    op.drop_table('scan_targets')
    op.drop_table('cve_catalog')
    # ### end Alembic commands ###
